import { SYSTEM_PATH } from "../constants.mjs";
import { RollerDiceSoNice } from "./roller-dice-so-nice.mjs";

export interface RollD20Options {
  actor: Actor | undefined | null;
  item: Item | undefined | null;

  /**
   * A user-friendly designation of the roll.
   */
  rollName: string;

  /**
   * Value of the attribute appropriate for the roll.
   */
  attribute: number;

  /**
   * Value of the skill appropriate for the roll.
   */
  skill: number;

  /**
   * If die value is greater or equal to this value, a complication occurs. Default is 20.
   */
  complicationThreshold: number;

  /**
   * The number of d20 to roll. Default is 2.
   */
  diceNum: number;

  /**
   * The number of successes required to consider the roll successful. Default is 1.
   */
  difficulty: number;

  /**
   * True if the actor has the appropriate focus for the roll; false otherwise. Default is false.
   */
  hasFocus?: boolean;
}

export interface RollD20DieResult {
  /**
   * The raw result of the Die.
   */
  result: number;

  /**
   * The number of successes generated by the die.
   */
  successes: number;

  /**
   * The number of complications generated by the die.
   */
  complications: number;

  /**
   * True if the die has been rerolled; false otherwise.
   */
  reroll: boolean;
}

export interface RollD20Result extends RollD20Options, Record<string, unknown> {
  /**
   * If die value is lower or equal than this value, die has rolled a success. Default is 0.
   */
  successThreshold: number;

  /**
   * If die value is lower or equal than this value, die has rolled a critical success. Default is 1.
   */
  critThreshold: number;

  /**
   * The Roll instance to parse.
   */
  roll: Roll;

  /**
   * The indices of the dice to reroll.
   */
  rerollIndices?: number[];

  /**
   * Result of the roll, die by die.
   */
  diceRolled?: RollD20DieResult[];

  /**
   * The number of successes generated by the roll.
   */
  successes?: number;

  /**
   * The number of complications generated by the roll.
   */
  complications?: number;
}

export class RollerD20 {
  private static _defaultOptions: RollD20Options = {
    actor: null,
    item: null,
    rollName: "Roll xD20",
    attribute: 0,
    skill: 0,
    complicationThreshold: 20,
    diceNum: 2,
    difficulty: 1,
    hasFocus: false,
  };

  public static async rollD20(
    options: RollD20Options = RollerD20._defaultOptions
  ): Promise<RollD20Result> {
    // patch options
    RollerD20._patchOptions(options);

    const successThreshold = options.attribute + options.skill;
    const critThreshold = options.hasFocus ? options.skill : 1;

    const roll = new Roll(`${options.diceNum}d20`);
    roll.evaluate({ async: true });

    RollerDiceSoNice.showDiceSoNice(roll);

    const parseOptions: RollD20Result = {
      ...options,
      successThreshold,
      critThreshold,
      roll,
    };

    const result = await RollerD20.parseRoll(parseOptions);

    return result;
  }

  public static async parseRoll(result: RollD20Result): Promise<RollD20Result> {
    if (!result.diceRolled) {
      result.diceRolled = [];
    }

    result.critThreshold = Math.max(result.critThreshold, 1);

    const {
      roll,
      successThreshold,
      complicationThreshold,
      critThreshold,
      diceRolled,
      rerollIndices,
    } = result;

    let i: number = 0;
    let successesNum = 0;
    let complicationsNum = 0;

    roll.dice.forEach((d) => {
      d.results.forEach((r) => {
        let diceSuccess = 0;
        let diceComplication = 0;

        if (r.result <= successThreshold) {
          diceSuccess++;
        }

        if (r.result <= critThreshold) {
          diceSuccess++;
        }

        if (r.result >= complicationThreshold) {
          diceComplication = 1;
        }

        // If there are no rollIndexes sent then it is a new roll.
        // Otherwise it's a re-roll and we should replace dices at given
        // indexes
        if (!rerollIndices?.length) {
          diceRolled.push({
            successes: diceSuccess,
            reroll: false,
            result: r.result,
            complications: diceComplication,
          });
        } else {
          diceRolled[rerollIndices[i]] = {
            successes: diceSuccess,
            reroll: true,
            result: r.result,
            complications: diceComplication,
          };

          successesNum += diceSuccess;
          complicationsNum += diceComplication;

          i++;
        }
      });
    });

    result.successes = successesNum;
    result.complications = complicationsNum;

    await RollerD20.sendToChat(result);

    return result;
  }

  static async sendToChat(result: RollD20Result): Promise<void> {
    const { actor, roll } = result;

    const html = await renderTemplate(
      `${SYSTEM_PATH}/templates/chat/roll-d20.hbs`,
      result
    );

    let chatData = {
      content: html,
      flags: { rollD20: result },
      roll,
      rollMode: game.settings.get("core", "rollMode"),
      speaker: ChatMessage.getSpeaker({ actor: actor }),
      user: game.user.id,
    };

    ChatMessage.applyRollMode(chatData, game.settings.get("core", "rollMode"));

    await ChatMessage.create(chatData);
  }

  private static _patchOptions(options: RollD20Options): void {
    const defaultOptions = RollerD20._defaultOptions;

    if (typeof options.rollName !== "string") {
      options.rollName = defaultOptions.rollName;
    }

    if (typeof options.attribute !== "number") {
      options.attribute = defaultOptions.attribute;
    }

    if (typeof options.skill !== "number") {
      options.skill = defaultOptions.skill;
    }

    if (typeof options.complicationThreshold !== "number") {
      options.complicationThreshold = defaultOptions.complicationThreshold;
    }

    if (typeof options.diceNum !== "number") {
      options.diceNum = defaultOptions.diceNum;
    }

    if (typeof options.difficulty !== "number") {
      options.difficulty = defaultOptions.difficulty;
    }

    if (typeof options.hasFocus !== "boolean") {
      options.hasFocus = defaultOptions.hasFocus;
    }
  }
}
